RedisExchanceAPI.Web/Models/ErrorViewModel.cs
namespace RedisExchanceAPI.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RedisExchanceAPI.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchanceAPI.Web.Controllers
{
    public class BaseController : Controller
    {
        private readonly RedisService _redis;
        protected readonly IDatabase _db;

        public BaseController(RedisService redis)
        {
            _redis = redis;
            _db = redis.GetDB(1);
        }
    }
}

RedisExchanceAPI.Web/Controllers/HashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;
using System.Xml.Linq;

namespace RedisExchanceAPI.Web.Controllers
{
    public class HashTypeController : BaseController
    {
        public string hashKey { get; set; } = "sozluk";
        public HashTypeController(RedisService redis) : base(redis)
        {
        }

        public IActionResult Index()
        {
            Dictionary<string, string> list = new Dictionary<string, string>();

            if (_db.KeyExists(hashKey))
            {
                _db.HashGetAll(hashKey).ToList().ForEach(x =>
                {
                    list.Add(x.Name, x.Value);
                });
            }

            return View(list);
        }
        [HttpPost]
        public IActionResult Add(string name,string val)
        {
            _db.HashSet(hashKey,name,val);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteItem(string name)
        {
            _db.HashDelete(hashKey, name);


            return RedirectToAction("Index");
        }
    }
}

RedisExchanceAPI.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchanceAPI.Web.Models;
using RedisExchangeApi.Web.Services;
using System.Diagnostics;

namespace RedisExchangeApi.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        RedisService _redisService;
        public HomeController(ILogger<HomeController> logger, RedisService redisService)
        {
            _logger = logger;
            _redisService = redisService;
        }

        public IActionResult Index()
        {
            _redisService.Connect();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RedisExchanceAPI.Web/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchanceAPI.Web.Controllers
{
    public class ListTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase _db;

        private string listKey="names";
        public ListTypeController(RedisService redis)
        {
            _redis = redis;
            _db = redis.GetDB(1);
        }
        public IActionResult Index()
        {
            List<string> nameList = new List<string>();
            if (_db.KeyExists(listKey))
            {
                _db.ListRange(listKey).ToList().ForEach(x =>
                {
                    nameList.Add(x.ToString());
                });
            }
            return View(nameList);
        }
        [HttpPost]
        public IActionResult Add(string name)
        {
            _db.ListRightPush(listKey,name);
            return RedirectToAction("Index");
        }


        public IActionResult DeleteItem(string name)
        {
            _db.ListRemoveAsync(listKey,name).Wait();
            return RedirectToAction("Index");
        }

        public IActionResult DeleteFirstItem()
        {
            _db.ListLeftPop(listKey);

            return RedirectToAction("Index");
        }

    }
}

RedisExchanceAPI.Web/Controllers/SetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchanceAPI.Web.Controllers
{
    public class SetTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase _db;

        private string listKey = "hashnames";
        public SetTypeController(RedisService redis)
        {
            _redis = redis;
            _db = redis.GetDB(2);
        }
        public IActionResult Index()
        {
            HashSet<string> namesList = new HashSet<string>();
            if (_db.KeyExists(listKey))
            {
                _db.SetMembers(listKey).ToList().ForEach(x =>
                {
                    namesList.Add(x.ToString());
                });
                  
            }
            return View(namesList);
        }
        [HttpPost]
        public IActionResult Add(string name)
        {
           
            _db.KeyExpire(listKey, DateTime.Now.AddMinutes(5));

            _db.SetAdd(listKey, name);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteItem(string name)
        {
            _db.SetRemoveAsync(listKey, name);


            return RedirectToAction("Index");
        }
    }
}

RedisExchanceAPI.Web/Controllers/SortedSetController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchanceAPI.Web.Controllers
{
    public class SortedSetController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase _db;

        private string listKey = "hashnames";
        public SortedSetController(RedisService redis)
        {
            _redis = redis;
            _db = redis.GetDB(2);
        }
        public IActionResult Index()
        {
            HashSet<string> list = new HashSet<string>();
            if (_db.KeyExists(listKey))
            {
                _db.SortedSetScan(listKey).ToList().ForEach(x =>
                {
                    list.Add(x.ToString());
                });
                
            }


            return View(list);
        }
        [HttpPost]
        public  IActionResult Add(string name,int score)
        {
            _db.KeyExpire(listKey, DateTime.Now.AddMinutes(1));
            _db.SortedSetAdd(listKey, name, score);
            return RedirectToAction("Index");
        }
         public async Task<IActionResult> DeleteItem(string name)
        {
            _db.SetRemoveAsync(listKey, name); 


            return RedirectToAction("Index");
        }
    }
}

RedisExchanceAPI.Web/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApi.Web.Controllers
{
    public class StringTypeController : Controller
    {
        private readonly RedisService _redis;
        private readonly IDatabase _db;
        public StringTypeController(RedisService redis)
        {
            _redis = redis;
            _db = redis.GetDB(0);
        }
        public IActionResult Index()
        {
            //var db = _redis.GetDB(0);
            //var db = _redisService.GetDB(0);
            _db.StringSet("name", "Mustafa Taşkıran");
            _db.StringSet("ziyaretci",100);

            return View();
        }
        public IActionResult Show()
        {
            //var value = _db.StringGet("name");

            var value = _db.StringGetRange("name",0, 3);
            
            //_db.StringIncrement("ziyaretci", 10);
            var count = _db.StringDecrementAsync("ziyaretci", 1).Result;
            _db.StringDecrementAsync("ziyaretci", 10).Wait();
            //if (value.HasValue)
            {
                ViewBag.value = value.ToString();
                ViewBag.count = count.ToString();
            }
            


            return View();
        }
    }
}

RedisExchanceAPI.Web/Views/HashType/Index.cshtml
@model Dictionary<string,string>
@{

}
<a asp-action="DeleteFirstItem">baştan sil</a>
<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <input type="text" name="val" />

    <button type="submit">Kaydet</button>


</form>
@foreach (var item in Model)
{
    <h2>@item.Key->@item.Value<a asp-action="DeleteItem" asp-route-name="@item.Key">Sil</a></h2>

}

RedisExchanceAPI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RedisExchanceAPI.Web/Views/ListType/Index.cshtml
@model List<string> 
@{

}
<a asp-action="DeleteFirstItem">baştan sil</a>
<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Kaydet</button>
   

</form> 
@foreach (var item in Model)
{
    <h2>@item<a asp-controller="ListType" asp-action="DeleteItem" asp-route-name="@item">Sil</a></h2>

}

RedisExchanceAPI.Web/Views/SetType/Index.cshtml
@model HashSet<string>
@{

}
<a asp-action="DeleteFirstItem">baştan sil</a>
<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <button type="submit">Kaydet</button>


</form>
@foreach (var item in Model)
{
    <h2>@item<a asp-controller="SetType" asp-action="DeleteItem" asp-route-name="@item">Sil</a></h2>

}

RedisExchanceAPI.Web/Views/SortedSet/Index.cshtml
@model HashSet<string>
@{

}
<a asp-action="DeleteFirstItem">baştan sil</a>
<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" />
    <input type="text" name="score" />

    <button type="submit">Kaydet</button>


</form>
@foreach (var item in Model)
{
    <h2>@item<a asp-controller="SortedSet" asp-action="DeleteItem" asp-route-name="@item">Sil</a></h2>

}